name = "Unison"
grammar = "unison"
path_suffixes = ["u"]
line_comments = ["-- "]
autoclose_before = "}])"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "{{", end = "}}", close = true, newline = true, not_in = ["literal_text"] },
    { start = "\"", end = "\"", close = true, newline = true, not_in = ["literal_text", "literal_char"] },
]
